# Generated by Django 3.0.3 on 2020-03-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('smtpserver', models.CharField(max_length=255)),
                ('smtpemail', models.EmailField(max_length=254)),
                ('smtppassword', models.CharField(max_length=50)),
                ('smtpport', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('facebook', models.CharField(max_length=80)),
                ('instagram', models.CharField(max_length=80)),
                ('twitter', models.CharField(max_length=80)),
                ('aboutus', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('references', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=5)),
            ],
        ),
    ]
