# Generated by Django 3.0.3 on 2020-03-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200330_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='smtpport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
