# Generated by Django 3.0.3 on 2020-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200404_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=10),
        ),
    ]
