# Generated by Django 3.0.3 on 2020-05-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200511_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Closed', 'Closed'), ('Read', 'Read')], default='New', max_length=10),
        ),
    ]
