# Generated by Django 3.0.3 on 2020-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200525_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Closed', 'Closed'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
