# Generated by Django 3.0.3 on 2020-06-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200530_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Closed', 'Closed'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
