# Generated by Django 3.0.3 on 2020-04-04 15:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_delete_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
