# Generated by Django 3.0.3 on 2020-04-04 15:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20200404_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
