# Generated by Django 3.0.3 on 2020-05-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20200510_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='category_id',
            new_name='category',
        ),
    ]
