# Generated by Django 3.0.3 on 2020-05-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20200510_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('rate', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('New', 'Yeni'), ('True', 'Evet'), ('False', 'Hayır')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.User')),
            ],
        ),
    ]
