# Generated by Django 3.0.3 on 2020-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20200510_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
