# Generated by Django 3.0.3 on 2020-05-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20200529_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/hotel/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='imagehotel',
            name='image',
            field=models.ImageField(upload_to='images/hotel/'),
        ),
        migrations.AlterField(
            model_name='imageroom',
            name='image',
            field=models.ImageField(upload_to='images/room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/room/'),
        ),
    ]
