# Generated by Django 3.0.3 on 2020-05-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
